### Function in Multiple Variables

In [6]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.optimize import fsolve

#### Q2. Solve the function $x^{2} + y^{2} = 16$ 

In [24]:
def myfunction(z):
    x=z[0]
    y=z[1]
    F=np.empty((2))
    F[0]=x**2+y**2 -16
    return F
zGuess=np.array([3,2])
z=fsolve(myfunction,zGuess)
print(z)

[3. 2.]


In [13]:
def myfunction(z):
    x=z[0]
    y=z[1]
    w=z[2]
    F=np.empty((3))
    F[0]=x**2+y**2 + w**2
    return F
zGuess=np.array([3,4,2])
z=fsolve(myfunction,zGuess)
print(z)

[3. 4. 2.]


In [25]:
def myfunction(z):
    x=z[0]
    y=z[1]
    w=z[2]
    F=np.empty((3))
    F[0]=x**2+y**2 -20
    F[1]=y - x**2
    F[2]=w+5 -x*y
    return F
zGuess=np.array([1,1,1])
z=fsolve(myfunction,zGuess)
print(z)

[2. 4. 3.]


In [26]:
from math import exp
def equations(vars):
    x,y=vars
    eq1 = x+y**2 -4
    eq2= exp(x) + x*y -3
    return [eq1, eq2]

x,y= fsolve(equations, (1,1))
print("The solution to the set of equations are: x=%f, y=%f"%(x,y))
eq1 = x+y**2 -4
eq2= exp(x) + x*y -3
print('x+y**2 -4 = %d'%(eq1))
print('exp(x) + x*y -3 =%d' %(eq2))


The solution to the set of equations are: x=0.620345, y=1.838384
x+y**2 -4 = 0
exp(x) + x*y -3 =0


### Multiple Equations in mutiple unkowns

### Sympy is a package for symbolic solutions in Python that can be usd to solve systems of equations

### Q3. Solve the following two equations in two unknowns.
$h(y,z)=y+2z,
g(y,z)=\frac{sin(y)}{z}$
Use $y_{0}=1$, and $zy_{0}=2$ as an initial guess.


In [27]:
def hg(yz):
    y=yz[0]
    z=yz[1]
    
    h=y+2*z
    g=np.sin(y)/z
    
    return np.array([h,g])

yz0= np.array([1,2])
yz=fsolve(hg,yz0)
yz

array([ 9.42477796, -4.71238898])

### Q4. Solve the following system of three equations in three unknowns:
$x^{2} + y^{2} =1$ <br>
$xy + yz =-1.1$ <br>
$y^{2} + z^{2} =2$ <br>
A reasonable guess for all variables is $x=y=z=2$

In [29]:
def f(xyz):
    x=xyz[0]
    y=xyz[0]
    z=xyz[0]
    f0= x**2 + y**2 -1
    f1= x*y + y*z +1.1
    f2= y**2 + z**2 -2
    
    return np.array([f0,f1,f2])
xyz0=np.array([2.0,2,2])

xyz=fsolve(f,xyz0)
x=xyz[0]
y=xyz[1]
z=xyz[2]

print(x,y,z, f(xyz))

0.5627316351525624 130055.85554248655 187461.64644362385 [-0.36666621  1.73333379 -1.36666621]
