## MATRICES

Matrix is a 2-D array where numbers, symbols or expressions are arranged into rows and columns. Using the concept of lists , one can easily define a matrix in Python. <br> We define two matrices A and B

In [24]:
A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[9,8,7],[6,5,4],[3,2,1]]
print(A)
print(B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[9, 8, 7], [6, 5, 4], [3, 2, 1]]


In [25]:
A[0][0] # A single element is called

1

In [26]:
A+B

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [9, 8, 7], [6, 5, 4], [3, 2, 1]]

In [27]:
2*A

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [28]:
A*B # The multiplication operator does not work when the matrix is defined as list of lists 

TypeError: can't multiply sequence by non-int of type 'list'

In [29]:
A**2 # The ** operator or pow() does not work when the matrix is defined as list of lists

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [30]:
A[0].append(10)
print(A)

[[1, 2, 3, 10], [4, 5, 6], [7, 8, 9]]


The matrix A being defined as a list of lists, Python supports adding a element to a row or column, which falsifies the very definition of a matrix

Through the above commands, we can see that even though it is possible to define matrix as a list of lists, matrix multiplication is not straight forward as desired.

### Working with matrices can be made easier in Python by using NumPy package

NumPy is a library consisting of mutlidimensional array objects and package of functions for processing those array. NumPy stands for Numerical Python. The following operations can be performed using NumPy 
1. Mathematical and logical operations on arrays.
2. Fourier tranforms and routines for shape manipulation.
3. Operations related to linear algebra.
We can import the NumPy package using one of the following syntax - <br>
import numpy <br>
import numpy as np (preferred)<br>
from numpy import*

In [2]:
import numpy as np

NumPy provides the function array() and matrix() to define a matrix.

In [32]:
A1 = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(A1)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [33]:
M1 = np.matrix([[1,2,3],[3,4,5],[5,6,7]])
print(M1)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


### The differences between np.array() and np.matrix() are the following:

1. np.array() provides an n-dimensional array while np.matrix() is strictly 2-D
2. The * and ** operators performs element wise operations in array while in matrix they are used for multiplication and finding powers.

We will use np.matrix() to work with matrices.

### Frequent errors while defining a matrix are shown below

In [34]:
N = np.matrix([[1,2,3],[3,4,5],[5,6,7]]) # The package isn't imported

In [36]:
import numpy as np
N = np.matrix([1,2,3],[3,4,5],[5,6,7]) # Another square bracket missing

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [37]:
N = np.matrix([[1,2,3],[3,4,5],[5,6,7]])
N

matrix([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

### Matrix Manipulation

The order of the matrix can be found using shape function.

In [38]:
M1.shape

(3, 3)

In [39]:
M1.shape[0] # Number of rows

3

In [40]:
M1.shape[1] # Number of columns

3

The number of elements in the matrix is given by size function.

In [41]:
M1.size # Number of rows X number of columns

9

In [42]:
N.size # Number of rows X number of columns

9

The function zeros creates an array of zeros.

In [43]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

By default the zeros() and ones() function gives font value, so the output is 0 or 1, if np.zeros((4,4) dtype=int) or simply(np.zeros(4,4),int) is given that we get it as ) or 1

Note that zeros produces an array of zeros rather than a matrix.

### Matrix Operations

The + operator and the function add() can be used to add corresponding elements of two matrices.

In [5]:
D = np.matrix([[1,2,3],[3,4,5],[5,6,7]]) # defining 3 matrices
print("The matrix D = ",D)
E = np.matrix([[3,2,9],[3,8,1],[1,0,7]])
print("The matrix E = ",E)
F = np.matrix([[11,2,3],[3,10,7],[5,8,2]])
print("The matrix F= ",F)

The matrix D =  [[1 2 3]
 [3 4 5]
 [5 6 7]]
The matrix E =  [[3 2 9]
 [3 8 1]
 [1 0 7]]
The matrix F=  [[11  2  3]
 [ 3 10  7]
 [ 5  8  2]]


In [47]:
D+E

matrix([[ 4,  4, 12],
        [ 6, 12,  6],
        [ 6,  6, 14]])

In [48]:
np.add(D,E)

matrix([[ 4,  4, 12],
        [ 6, 12,  6],
        [ 6,  6, 14]])

The - operator and the function subtract() can be used to subtract corresponding elements of the second matrix from the first.

In [49]:
D-E

matrix([[-2,  0, -6],
        [ 0, -4,  4],
        [ 4,  6,  0]])

In [50]:
np.subtract(D,E)

matrix([[-2,  0, -6],
        [ 0, -4,  4],
        [ 4,  6,  0]])

The multiply() function is used for elementwise multiplication and * operator and .dot() function can be used for matrix multiplication.

In [51]:
np.multiply(D,E)

matrix([[ 3,  4, 27],
        [ 9, 32,  5],
        [ 5,  0, 49]])

In [52]:
D*E

matrix([[ 12,  18,  32],
        [ 26,  38,  66],
        [ 40,  58, 100]])

In [53]:
D.dot(E)

matrix([[ 12,  18,  32],
        [ 26,  38,  66],
        [ 40,  58, 100]])

The / operator and the function divide can be used for element wise matrix division.

In [54]:
E/D

matrix([[3. , 1. , 3. ],
        [1. , 2. , 0.2],
        [0.2, 0. , 1. ]])

In [55]:
np.divide(E,D)

matrix([[3. , 1. , 3. ],
        [1. , 2. , 0.2],
        [0.2, 0. , 1. ]])