### Solving System Of Equations

#### A linear equation n variables $x_1 , x_2 \ldots, x_n$ is an equation of the form 
#### $a_1x_1 + a_2x_2 + \ldots + a_nx_n =b$, where $a_1, a_2, \ldots, a_n$ and $b$ are constants. The constant $a_i$ is called coefficent of $x_i$

### A sytsem of linear equation is a finite collection of linear equation in same variable . <br>The following is a system of $m$ linear eqn in $n$ variables $x_1, x_2. \ldots, x_n$. <br>
#### $a_{11}x_1 + a_{12}x_2 +\ldots + a_{1n}x_n = b_1$<br>
#### $a_{21}x_1 + a_{22}x_2 +\ldots + a_{2n}x_n = b_2$<br>
#### $\ldots$<br>
#### $a_{m1}x_1 + a_{m2}x_2 +\ldots + a_{mn}x_n = b_m$

 In matrix notation a linear system is $AX=B$, where <br>  
$A=\begin{bmatrix}
a_{11}&a_{12}&\ldots&a_{1n} \\
a_{21}&a_{22}&\ldots&a_{2n} \\
\vdots& \\
a_{m1}&a_{m2}&\ldots&a_{mn}
\end{bmatrix}$ is the coefficient matrix ,

 $x=\begin{bmatrix}
 x_1 \\
 x_2 \\
 \vdots \\
 x_n \\
 \end {bmatrix}$ 
 and
 $B=\begin{bmatrix}
b_1 \\
 b_2 \\
\vdots \\
 b_m \\
 \end{bmatrix}$





In [5]:
import numpy as np

In [6]:
A=np.array([[1,2,-1],[2,1,4],[3,3,4]])
B=np.array([1,2,1])
np.linalg.solve(A,B)

array([ 7., -4., -2.])

In [7]:
A=np.matrix([[1,2,-1],[2,1,4],[3,3,4]])
B=np.matrix([1,2,1])
np.linalg.solve(A,B)

ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 1 is different from 3)

### This is because b is a $m \times $l matrix in the matrix equivalent of linear sytsem of equation

In [10]:
A=np.matrix([[1,2,-1],[2,1,4],[3,3,4]])
B=np.matrix([[1],[2],[1]])
np.linalg.solve(A,B)

matrix([[ 7.],
        [-4.],
        [-2.]])

### The function np.linalg.solve() works only if A is a non-singular matrix

In [12]:
A=np.matrix([[1,-1,1,-1],[1,-1,1,-1],[4,-4,4,0],[-2,2,-2,1]])
B=np.matrix([[2],[0],[4],[-3]])
np.linalg.solve(A,B)

LinAlgError: Singular matrix

## Exercise Problems
### Q1. Write a program to solve any system of linear equations(user input). Check whether the coefficient matrix is singular or not. If singular, print no solution. If non-singular, then print the inverse exist and solve the system of equation.

### Q2. Solve the following system of Linear Equations

### 1)
$x_1 + x_2 -x_3= -1$ <br>
$2x_1+x_2+4x_3=2$ <br>
$3x_1+3x_2+4x_3=1$

### 2)
$x_1- x_2+x_3-x_4=2$ <br>
$x_1-x_2+x_3+x_4=0$ <br>
$4x_1-4x_2+4x_3=4$ <br>
$-2x_1+2x_2-2x_3+x_4=-3$

In [9]:
import numpy as np
A=np.matrix([[1,2,-1],[2,1,4],[3,3,4]])
B=np.matrix([[-1],[2],[1]])
if np.linalg.det(A)!=0 and A.shape[0]==A.shape[1]:
    X = np.linalg.solve(A,B)
    print(X)
else:
    print("No solution")

[[ 1.66666667e+00]
 [-1.33333333e+00]
 [-3.70074342e-16]]


###  Find solution using inverse (X= A^{-1} * B)

### 3)
$x_1 +2x_2 -x_3 =1$ <br>
$2x_1+x_2 +5x_3 =2$ <br>
$3x_1+3x_2+4x_3=1$ <br>

### 4)
$x_1+2x_2 +x_3=4$ <br>
$4x_1+5x_2+6x_3=7$ <br>
$7x_1+8x_2+9x_3=10$

In [1]:
import numpy as np
A=np.matrix([[1,2,-1],[2,1,5],[3,3,4]])
B=np.matrix([[1],[2],[1]])
if np.linalg.det(A)!=0 and A.shape[0]==A.shape[1]:
    X = np.linalg.solve(A,B)
    print(X)
else:
    print("No solution")

[[-1.04293886e+16]
 [ 6.63688366e+15]
 [ 2.84437871e+15]]


In [2]:
import numpy as np
A=np.matrix([[1,2,1],[4,5,6],[7,8,9]])
B=np.matrix([[4],[7],[10]])
if np.linalg.det(A)!=0 and A.shape[0]==A.shape[1]:
    X = np.linalg.solve(A,B)
    print(X)
else:
    print("No solution")

[[-2.00000000e+00]
 [ 3.00000000e+00]
 [-3.48927236e-16]]


### 5) <br>
$x_1+ 3x_2-5x_3=1$ <br>
$4x_1-2x_2+x_3=2$

### Exercises:
#### Suppose a fruit seller sold 20 mangoes and 10 oranges in one day for a total of 350 dollar. The next day he sold 17 mangoes and 22 oranges for 500 dollars. If the price of the fruits remained unchanged on both the days, what was the price of one mango and one orange?

#### Let the cost of 1 mango be $x_1$ and cost of 1 orange be $x_2$

$20x_1 + 10x_2 =350$ <br>
$17x_1 + 22x_2 = 500$

In [12]:
A=np.matrix([[20,10],[17,22]])
B=np.matrix([[350],[500]])
if np.linalg.det(A)!=0 and A.shape[0]==A.shape[1]:
    X = np.linalg.solve(A,B)
    print(X)

[[10.]
 [15.]]
