## Transpose of a matrix

### Transpose of a matrix can be found using transpose() function and .T operator.

In [6]:
D.transpose()


matrix([[1, 3, 5],
        [2, 4, 6],
        [3, 5, 7]])

In [8]:
np.transpose(D)

matrix([[1, 3, 5],
        [2, 4, 6],
        [3, 5, 7]])

In [9]:
D.T

matrix([[1, 3, 5],
        [2, 4, 6],
        [3, 5, 7]])

## Upper and Lower Triangular Matrix

In [2]:
import numpy as np
D = np.matrix(([1,2,3,],[3,4,5],[5,6,7])) # defining 3 matrices
print("The matrix D = \n",D)

The matrix D = 
 [[1 2 3]
 [3 4 5]
 [5 6 7]]


In [3]:
UT = np.triu(D) ##  triu() is the function that is used to get the upper triangular matrix of a matrix 
print(UT)

[[1 2 3]
 [0 4 5]
 [0 0 7]]


In [5]:
LT = np.tril(D) ## tril() is the function that is used to get the lower triangular matrix of a matrix
print(LT)

[[1 0 0]
 [3 4 0]
 [5 6 7]]


### numpy.linalg

NumPy package contains numpy.linalg module that provides various functions required for linear algebra.
One can find:

$\bullet$ rank, determinant, trace, inverse etc, of an array <br>
$\bullet$ eigen values of matrices <br>
$\bullet$ matrix and vector products ( dot,inner,outter,etc. product), matrix exponentiation,<br>
$\bullet$ solve linear equations and much more!

## Determinant of a Matrix

In [7]:
import numpy as np
D = np.matrix(([1,2,3],[3,4,5],[1,2,4]))
print("The matrix D = ",D)

The matrix D =  [[1 2 3]
 [3 4 5]
 [1 2 4]]


In [8]:
determinant = np.linalg.det(D)
print("The determinant of the matrix D is :",determinant)  

The determinant of the matrix D is : -2.0000000000000004


# Inverse of a matrix

In [11]:
X = np.matrix([[1,2],[4,9]])
print("The matrix X =\n",X)
Y = X**-1
print(Y)

The matrix X =
 [[1 2]
 [4 9]]
[[ 9. -2.]
 [-4.  1.]]


In [12]:
D**-1

matrix([[-3. ,  1. ,  1. ],
        [ 3.5, -0.5, -2. ],
        [-1. ,  0. ,  1. ]])

In [16]:
I = np.linalg.inv(X)
print("The inverse of the matrix X is: \n",I)

The inverse of the matrix X is: 
 [[ 9. -2.]
 [-4.  1.]]


In [14]:
Inverse = np.linalg.inv(D)
print("The inverse of the matrix D is:\n",Inverse)

The inverse of the matrix D is:
 [[-3.   1.   1. ]
 [ 3.5 -0.5 -2. ]
 [-1.   0.   1. ]]


# Eigen Values

In [20]:
import numpy as np
D = np.matrix([[1,2,3],[3,4,5],[5,6,7]])
print("The matrix D =\n",D)
eigen_values = np.linalg.eigvals(D)
print("The eigen values of the matrix D is: ",eigen_values)


The matrix D =
 [[1 2 3]
 [3 4 5]
 [5 6 7]]
The eigen values of the matrix D is:  [ 1.29282032e+01 -9.28203230e-01  9.10085294e-16]


In [22]:
D = np.matrix([[3,0,0],[0,4,0],[0,0,7]])
print("The matrix D = \n",D)
eigen_values = np.linalg.eigvals(D)
print("The eigen values of the matrix D is: ",eigen_values)

The matrix D = 
 [[3 0 0]
 [0 4 0]
 [0 0 7]]
The eigen values of the matrix D is:  [3. 4. 7.]


HW<br>
Q) Find the transpose, determinant, eigenvalues of: <br>
    1) Identity matrix <br>
    2) Any diagonal matrix <br>
    3) Any Upper Triangular matrix <br>
    4) Any Singular matrix <br>
    Analyze their properties.

In [3]:
import numpy as np
identity_matrix=np.matrix([[1,0,0],[0,1,0],[0,0,1]])
print("Identity Matrix \n", identity_matrix)
eigen_values = np.linalg.eigvals(identity_matrix)
print("The eigen values of the identity matrix are: ",eigen_values)
determinant = np.linalg.det(identity_matrix)
print("The determinant of the identity matrix D is :",determinant)
identity_matrix.transpose()

Identity Matrix 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
The eigen values of the identity matrix are:  [1. 1. 1.]
The determinant of the identity matrix D is : 1.0


matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [4]:
diagonal_matrix=np.matrix([[2,0,0],[0,3,0],[0,0,4]])
print("Diagonal Matrix \n", diagonal_matrix)
eigen_values = np.linalg.eigvals(diagonal_matrix)
print("The eigen values of the identity matrix are: ",eigen_values)
determinant = np.linalg.det(diagonal_matrix)
print("The determinant of the diagonal matrix is :",determinant)
diagonal_matrix.transpose()

Diagonal Matrix 
 [[2 0 0]
 [0 3 0]
 [0 0 4]]
The eigen values of the identity matrix are:  [2. 3. 4.]
The determinant of the diagonal matrix is : 23.999999999999993


matrix([[2, 0, 0],
        [0, 3, 0],
        [0, 0, 4]])

In [16]:
D = np.matrix(([1,2,3,],[3,4,5],[5,6,7])) # defining 3 matrices
print("The matrix = \n",D)
print("Upper triangle =")
UT = np.triu(D) ##  triu() is the function that is used to get the upper triangular matrix of a matrix 
print(UT)
eigen_values = np.linalg.eigvals(UT)
print("The eigen values of the identity matrix are: ",eigen_values)
determinant = np.linalg.det(UT)
print("The determinant of the diagonal matrix is :",determinant)
UT.transpose()

The matrix = 
 [[1 2 3]
 [3 4 5]
 [5 6 7]]
Upper triangle =
[[1 2 3]
 [0 4 5]
 [0 0 7]]
The eigen values of the identity matrix are:  [1. 4. 7.]
The determinant of the diagonal matrix is : 27.999999999999996


array([[1, 0, 0],
       [2, 4, 0],
       [3, 5, 7]])

In [7]:
D = np.matrix(([3,8,1],[-4,1,1],[-4,1,1]))
determinant = np.linalg.det(D)
print("The determinant of the Singular matrix is :",determinant)
eigen_values = np.linalg.eigvals(D)
print("The eigen values of the Singular matrix are: ",eigen_values)
D.transpose()

The determinant of the Singular matrix is : 0.0
The eigen values of the Singular matrix are:  [2.50000000e+00+5.97913037j 2.50000000e+00-5.97913037j
 6.82496752e-17+0.j        ]


matrix([[ 3, -4, -4],
        [ 8,  1,  1],
        [ 1,  1,  1]])