In [4]:
import numpy as np
A=np.matrix([[1,2,3],[3,4,5],[6,7,8]])
B=np.matrix([[1,8,3],[8,1,5],[1,3,8]])
print('Matrix A:\n', A)
print('Matrix B:\n', B)
ch=int(input("Enter your choice"))
if ch==1:
    q=A+B
    print("Sum of Matrices", q)
if ch==2:
    q=A-B
    print("Difference of Matrices",q)
if ch==3:
    q=A*B
    print("Product of Matrices",q)
if ch==4:
    q=np.linalg.det(A)
    print("Determinanat of Matrix A", q)
if ch==5:
    q=np.transpose(A)
    print("Transpose of Matrix", q)

Matrix A:
 [[1 2 3]
 [3 4 5]
 [6 7 8]]
Matrix B:
 [[1 8 3]
 [8 1 5]
 [1 3 8]]
Enter your choice5
Transpose of Matrix [[1 3 6]
 [2 4 7]
 [3 5 8]]


In [9]:
import numpy as np
from scipy.optimize import fsolve
def f(xyz):
    x=xyz[0]
    y=xyz[0]
    f0= x**2 + y**2 -5
    f1= y -3*x +5
    
    return np.array([f0,f1])
xyz0=np.array([1,1])

xyz=fsolve(f,xyz0)
x=xyz[0]
y=xyz[1]

print(x,y, f(xyz))

1.6593131612670047 -972.7785618780803 [0.50664033 1.68137368]
