## Identity Matrix
### Verify the following properties by suitable examples:
 #### Symmetric-Transpose of identity matrix is itself
 #### Identity Matrix is nonsingular
 ####   Inverse of Identity Matrix is itself
 ####   EigenValues are all 1's
 ####  Multiplying any matrix by the unit matrix, gives the matrix itself.
 ####   We always get an identity Matrix after multiplying two inverse matrices.

In [2]:
import numpy as np
I=np.matrix([[1,0,0],[0,1,0],[0,0,1]])
print("Identity Matrix", I)
trans=np.transpose(I)
print("Transpose Matrix", trans)
determinant=np.linalg.det(I)
print("Determinant", determinant)
inv=np.linalg.inv(I)
print("Inverse", inv)
eigen_values=np.linalg.eigvals(I)
print("Eigen Values", eigen_values)
A=np.matrix([[1,0,0],[0,5,0],[0,0,9]])
print("A=\n", A)
print("A*I=\n", A*I)
A_i=np.linalg.inv(A)
B=A*(A_i)
print("A*A^-1 =\n", B)

Identity Matrix [[1 0 0]
 [0 1 0]
 [0 0 1]]
Transpose Matrix [[1 0 0]
 [0 1 0]
 [0 0 1]]
Determinant 1.0
Inverse [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Eigen Values [1. 1. 1.]
A=
 [[1 0 0]
 [0 5 0]
 [0 0 9]]
A*I=
 [[1 0 0]
 [0 5 0]
 [0 0 9]]
A*A^-1 =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Diagonal Matrix

### Verify the following properties by suitable examples:
###    Addition, Multiplication of diagonal matrix gives a diagonal Matrix again:
###       diag(a1,...,an) + diag(b1,...,bn)= diag(a1+b1,...,an+bn)
### diag(a1,...,an) * diag(b1,...,bn)= diag(a1*b1,...,an*bn)
### Symmetric-Transpose of Diagonal matrix is itself
### Determinant of diag(a1, ..., 
### Identity Matrix is nonsingular if diagonal entries are all non-zero
### Eigen Values are diagonal Entries

In [6]:
D1=np.matrix([[1,0,0],[0,1,0],[0,0,1]])
D2=np.matrix([[4,0,0],[0,5,0],[0,0,6]])
print("D1=\n", D1)
print("D2=\n", D2)
D=D1+D2
C=D1+D2
print("D1+D2 =\n", D)
print("D1*D2 =\n", C)
trans=np.transpose(D1)
print("Transpose Matrix", trans)
determinant=np.linalg.det(D1)
print("Determinant", determinant)
inv=np.linalg.inv(D1)
print("Inverse", inv)
eigen_values=np.linalg.eigvals(D1)
print("Eigen Values", eigen_values)

D1=
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
D2=
 [[4 0 0]
 [0 5 0]
 [0 0 6]]
D1+D2 =
 [[5 0 0]
 [0 6 0]
 [0 0 7]]
D1*D2 =
 [[5 0 0]
 [0 6 0]
 [0 0 7]]
Transpose Matrix [[1 0 0]
 [0 1 0]
 [0 0 1]]
Determinant 1.0
Inverse [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Eigen Values [1. 1. 1.]


### On adding two upper triangle matrices, the result will be an upper triangular matrix itself
### Multiplying two upper triangular matrices, the result will be an upper triangular matrix.
### The transpose of an upper triangular matrix will be a lower triangular matrix
### The upper triangular matrix will remain an upper triangular matrix if inversed
### Determinant of diag(a1,... an)= a1*a2 ... an
### Upper triangular matrix is non-singular if diagonal entries are non-zero
### Eigen Values are diagonal Entries

In [8]:
U1=np.matrix([[1,4,5],[0,2,6],[0,0,3]])
U2=np.matrix([[1,0,0],[0,1,0],[0,0,1]])
print("U1=\n", D1)
print("U2=\n", D2)
U=U1+U2
V=U1+U2
print("U1+U2 =\n", U)
print("U1*U2 =\n", V)
trans=np.transpose(U1)
print("Transpose Matrix", trans)
determinant=np.linalg.det(U1)
print("Determinant", determinant)
inv=np.linalg.inv(U1)
print("Inverse", inv)
eigen_values=np.linalg.eigvals(U1)
print("Eigen Values", eigen_values)

U1=
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
U2=
 [[4 0 0]
 [0 5 0]
 [0 0 6]]
U1+U2 =
 [[2 4 5]
 [0 3 6]
 [0 0 4]]
U1*U2 =
 [[2 4 5]
 [0 3 6]
 [0 0 4]]
Transpose Matrix [[1 0 0]
 [4 2 0]
 [5 6 3]]
Determinant 6.0
Inverse [[ 1.         -2.          2.33333333]
 [ 0.          0.5        -1.        ]
 [ 0.          0.          0.33333333]]
Eigen Values [1. 2. 3.]


## Singular Matrix 

### The determinant of a singular matrix is zero
### A non-invertible matrix is referred to as singular matrix, i.e., when the determinant of a matrix is zero multiplicative inverse for this matrix
### Product of singular and non-singular matrix gives singular matrix


In [ ]:
s=np.matrix[[1,4,7],[1,4,2],[2,3,0]]
print("Singular Matrix =\n", s)
trans=np.transpose(s)
print("Transpose Matrix =\n", trans)


### RANK OF A MATRIX

linalg.matrix_rank(A) # Returns the matrix rank

In [5]:
from numpy.linalg import matrix_rank
I=np.eye(4)
print(I)
r=matrix_rank(I)
print("Rank", r)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Rank 4


In [15]:
o=np.matrix([[1,2,3,4],[0,-1,0,-1],[2,4,6,8]])
print(o)
rank=matrix_rank(o)
print("Rank", rank)

[[ 1  2  3  4]
 [ 0 -1  0 -1]
 [ 2  4  6  8]]
Rank 2


### Find the rank of the matrix A by using the row echelon form

In [18]:
A=np.matrix([[1,2,3],[2,-1,4],[3,0,5]])
print(A)
rank=matrix_rank(A)
print("Rank", rank)

[[ 1  2  3]
 [ 2 -1  4]
 [ 3  0  5]]
Rank 3


In [19]:
A=np.matrix([[1,2,3],[2,3,4],[3,5,4]])
print(A)
rank=matrix_rank(A)
print("Rank ", rank)

[[1 2 3]
 [2 3 4]
 [3 5 4]]
Rank  3


In [20]:
A=np.matrix([[5,6],[7,8]])
print(A)
rank=matrix_rank(A)
print("Rank", rank)

[[5 6]
 [7 8]]
Rank 2


In [22]:
I=np.eye(4);
I[3,3]=0
print(I)
r=matrix_rank(I)
print("Rank", r)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
Rank 3


In [23]:
matrix_rank(np.ones((4,)))
1
matrix_rank(np.zeros((4,)))

0